### ISSUE TITLE
Meta Issue #1

### ISSUE THREAD

**Issue by arcturus5340** [arcturus5340/Conways_Game_of_Life#1]
This meta issue includes all the currently known issues:
- [ ]  __divide__ function bug fix
- [ ] filling the file ****README.md****
- [ ] code refactoring to improve code readability
